version: '2'
services:
  lnd:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    user: '10000'
    labels:
      lagoon.type: basic-persistent
      lagoon.persistent: /app/storage
      lagoon.service.usecomposeports: true
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 8080
      LAGOON_ROUTE: http://lnd.docker.amazee.io
    volumes:
      - ./storage:/app/storage:delegated
    env_file:
      - .env.local
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port lnd 8080`
      - "10009" # exposes the port 10009 with a random local port, find it with `docker-compose port lnd 10009`

  tor:
    networks:
      - amazeeio-network
      - default
    build:
      context: tor
      dockerfile: Dockerfile
    user: '10000'
    labels:
      lagoon.type: worker-persistent
      lagoon.persistent: /data
      lagoon.persistent.name: lnd

networks:
  amazeeio-network:
    external: true
