---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    lagoon.sh/branch: main
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: cli
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: cli-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: cli
    lagoon.sh/service-type: cli-persistent
    lagoon.sh/template: cli-persistent-0.1.0
  name: cronjob-cli-drush-cron2
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            lagoon.sh/branch: main
            lagoon.sh/configMapSha: ""
            lagoon.sh/version: v2.7.x
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: cli
            app.kubernetes.io/managed-by: build-deploy-tool
            app.kubernetes.io/name: cli-persistent
            lagoon.sh/buildType: branch
            lagoon.sh/environment: main
            lagoon.sh/environmentType: production
            lagoon.sh/project: example-project
            lagoon.sh/service: cli
            lagoon.sh/service-type: cli-persistent
            lagoon.sh/template: cli-persistent-0.1.0
        spec:
          containers:
          - command:
            - /lagoon/cronjob.sh
            - drush cron
            env:
            - name: LAGOON_GIT_SHA
            - name: SERVICE_NAME
              value: cli
            envFrom:
            - configMapRef:
                name: lagoon-env
            image: harbor.example/example-project/main/cli:latest
            name: cronjob-cli-drush-cron2
            resources:
              requests:
                cpu: 10m
                memory: 100M
            volumeMounts:
            - mountPath: /var/run/secrets/lagoon/sshkey/
              name: lagoon-sshkey
              readOnly: true
            - mountPath: /app/docroot/sites/default/files//php
              name: nginx-php-twig
            - mountPath: /app/docroot/sites/default/files/
              name: nginx-php
          dnsConfig:
            options:
            - name: timeout
              value: "60"
            - name: attempts
              value: "10"
          enableServiceLinks: false
          imagePullSecrets:
          - name: lagoon-internal-registry-secret
          priorityClassName: lagoon-priority-production
          restartPolicy: Never
          volumes:
          - name: lagoon-sshkey
            secret:
              defaultMode: 420
              secretName: lagoon-sshkey
          - emptyDir: {}
            name: nginx-php-twig
          - name: nginx-php
            persistentVolumeClaim:
              claimName: nginx-php
  schedule: 5,35 * * * *
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 0
status: {}
