---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lagoon.sh/branch: main
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: redis
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: redis
    lagoon.sh/service-type: redis
    lagoon.sh/template: redis-0.1.0
  name: redis
spec:
  ports:
  - name: 6379-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lagoon.sh/branch: main
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: varnish
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: varnish
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: varnish
    lagoon.sh/service-type: varnish
    lagoon.sh/template: varnish-0.1.0
  name: varnish
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: controlport
    port: 6082
    protocol: TCP
    targetPort: controlport
  selector:
    app.kubernetes.io/instance: varnish
    app.kubernetes.io/name: varnish
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lagoon.sh/branch: main
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx-php
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: nginx-php-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: nginx-php
    lagoon.sh/service-type: nginx-php-persistent
    lagoon.sh/template: nginx-php-persistent-0.1.0
  name: nginx-php
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: nginx-php
    app.kubernetes.io/name: nginx-php-persistent
status:
  loadBalancer: {}
